######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 9 02:05:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += backend.h frontend.h middleend.h /usr/lib/oss/include/sys/soundcard.h
FORMS += frontend.ui
SOURCES += backend.cpp frontend.cpp main.cpp middleend.cpp
